version: "3"
services:
  web:
    container_name: bilingual-trans-web
    build:
      context: web
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: test
      RACK_ENV: test
  client:
    container_name: bilingual-trans-client
    build:
      context: client
      dockerfile: Dockerfile
