version: "3"
services:
  web:
    container_name: bilingual-trans-web
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/web
      - vendor:/web/vendor
      - client_dist:/web/public
    depends_on:
      - client
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      PORT: 3001
    ports:
      - "3001:3001"
  client:
    container_name: bilingual-trans-client
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
      - client_dist:/client/dist
    environment:
      # Node v18でエラーが発生する問題への対処.
      # webpack v6で不要になる想定
      # https://zenn.dev/yogarasu/articles/425732ff408d06
      NODE_OPTIONS: "--openssl-legacy-provider=value"
      PORT: 3001
volumes:
  vendor:
    driver_opts:
      type: none
      device: ${PWD}/web/vendor
      o: bind
  node_modules:
    driver_opts:
      type: none
      device: ${PWD}/client/node_modules
      o: bind
  client_dist:
