# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Spin-Up Docker Compose
      uses: yu-ichiro/spin-up-docker-compose-action@v1.1
      with:
        file: docker-compose.yml
        shared: true
        bake: true
        push: true
        up: false

  test-server:
    runs-on: ubuntu-latest
    needs:
      - setup_image
    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker Compose
      uses: yu-ichiro/spin-up-docker-compose-action@v1
      with:
        file: docker-compose.yml
        shared: true
        pull: true
        up: false
    - name: Run Tests for Server
      run: docker compose run web bundle exec spec

  test-client:
    runs-on: ubuntu-latest
    needs:
      - setup_image
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker Compose
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: docker-compose.yml
          shared: true
          pull: true
          up: false
      - name: Run Tests for Client
        run: docker compose run client yarn test
